import{describe,it,expect,afterEach}from'vitest';import fs from'node:fs';import path from'node:path';import YAML from'yaml';
import{sample,setup,T}from'./helpers';import{SafeFiles,machineBlock,safeName,START,END}from'../packages/obsidian-writer/src/safe-files';import{ObsidianWriter}from'../packages/obsidian-writer/src/index';import{aggregate}from'../packages/obsidian-writer/src/stats';
const opened:ReturnType<typeof setup>[]=[];const fresh=()=>{const x=setup();opened.push(x);return x;};afterEach(()=>{for(const x of opened.splice(0))x.close();});
function completed(x:ReturnType<typeof setup>){const s=x.engine.ingest(sample())!;x.engine.ingest(sample(T+10000));x.engine.finish('test-client',T+20000);return x.store.session(s.id)!;}
describe('non-destructive Obsidian synchronization',()=>{
 it('preserves exact text outside machine block including CRLF',()=>{const old='\uFEFF---\r\nai_minutes: 99\r\n---\r\n正文\r\n'+START+'\r\nold\r\n'+END+'\r\n我的笔记';const next=machineBlock(old,'new');expect(next.slice(0,next.indexOf(START)+START.length)).toBe(old.slice(0,old.indexOf(START)+START.length));expect(next.slice(next.indexOf(END))).toBe(old.slice(old.indexOf(END)));});
 it('append preserves original byte prefix',()=>{const old='人工内容\n';expect(machineBlock(old,'hello').startsWith(old)).toBe(true);});
 it.each([START,END,START+START+END,END+START])('rejects malformed markers %s',value=>expect(()=>machineBlock(value,'x')).toThrow());
 it.each(['../escape','../../escape','D:/outside'])('rejects path traversal %s',value=>{const x=fresh();expect(()=>new SafeFiles(x.config.vaultPath,x.dir,x.store).resolve(value)).toThrow();});
 it('creates stable Unicode session note without transcript',()=>{const x=fresh(),s=completed(x),writer=new ObsidianWriter(x.store,x.config,x.dir);writer.sync();const saved=x.store.session(s.id)!;expect(saved.notePath).toContain('高等数学');const text=writer.files.read(saved.notePath!)!;expect(text).toContain('summary_status: pending');expect(text).toContain('effective_minutes: 0.33');expect(text).not.toContain('原始私密消息');});
 it('repeated sync is idempotent without extra files or backups',()=>{const x=fresh();completed(x);const w=new ObsidianWriter(x.store,x.config,x.dir);w.sync();const count=x.store.db.prepare('SELECT count(*) n FROM sync_records').get()?.n;w.sync();expect(x.store.db.prepare('SELECT count(*) n FROM sync_records').get()?.n).toBe(count);});
 it('manual classification and topics survive next synchronization',()=>{const x=fresh(),s=completed(x),w=new ObsidianWriter(x.store,x.config,x.dir);w.sync();const p=x.store.session(s.id)!.notePath!;const full=w.files.resolve(p);fs.writeFileSync(full,fs.readFileSync(full,'utf8').replace('category: 其他','category: 我的课程').replace('topics: []','topics: [手工主题]'));w.sync();expect(x.store.session(s.id)?.category).toBe('我的课程');expect(aggregate(x.store,x.config.timezone)['2026-09-12'].categories['我的课程']).toBeCloseTo(1/3,3);});
 it('manual task completion is preserved',()=>{const x=fresh(),s=completed(x),w=new ObsidianWriter(x.store,x.config,x.dir);w.sync();const p=x.store.session(s.id)!.notePath!;const full=w.files.resolve(p);fs.writeFileSync(full,fs.readFileSync(full,'utf8').replace('## 下一次','## 下一次\n\n- [x] 人工完成'));w.sync();expect(w.files.read(p)).toContain('- [x] 人工完成');});
 it('backs up existing files and undo restores exact bytes',()=>{const x=fresh(),f=new SafeFiles(x.config.vaultPath,x.dir,x.store);f.write('note.md','原始\r\n',null);f.write('note.md','新内容','原始\r\n');const row=x.store.db.prepare('SELECT id FROM sync_records ORDER BY rowid DESC LIMIT 1').get()!;f.undo(String(row.id));expect(f.read('note.md')).toBe('原始\r\n');});
 it('does not overwrite a file edited since read',()=>{const x=fresh(),f=new SafeFiles(x.config.vaultPath,x.dir,x.store);f.write('note.md','original',null);fs.writeFileSync(f.resolve('note.md'),'manual');expect(()=>f.write('note.md','updated','original')).toThrow('FILE_EDIT_CONFLICT');expect(f.read('note.md')).toBe('manual');});
 it('undo refuses subsequent manual edits',()=>{const x=fresh(),f=new SafeFiles(x.config.vaultPath,x.dir,x.store);f.write('note.md','original',null);const row=x.store.db.prepare('SELECT id FROM sync_records').get()!;fs.writeFileSync(f.resolve('note.md'),'manual');expect(()=>f.undo(String(row.id))).toThrow('FILE_EDIT_CONFLICT');});
 it('recovers a prepared journal after atomic rename',()=>{const x=fresh(),f=new SafeFiles(x.config.vaultPath,x.dir,x.store);f.write('note.md','done',null);x.store.db.prepare("UPDATE sync_records SET status='prepared'").run();f.recover();expect(x.store.db.prepare('SELECT status FROM sync_records').get()?.status).toBe('applied');});
 it('uses numeric YAML fields and valid Chinese file names',()=>{const x=fresh(),s=completed(x),w=new ObsidianWriter(x.store,x.config,x.dir);s.conversationTitle='CON: 高数 / "雅可比"?';x.store.save(s);w.sync();const file=x.store.session(s.id)!.notePath!;expect(path.basename(file)).not.toMatch(/[<>:"/\\|?*]/);const data=YAML.parse(w.files.read(file)!.split('---')[1]);expect(typeof data.effective_minutes).toBe('number');expect(Array.isArray(data.topics)).toBe(true);expect(safeName('CON')).toBe('_CON');});
 it('splits active time at local midnight',()=>{const x=fresh(),t=Date.parse('2026-09-12T15:59:50Z');x.engine.ingest(sample(t,{lastInteraction:t}));x.engine.finish('test-client',t+20000);const stats=aggregate(x.store,x.config.timezone);expect(stats['2026-09-12'].minutes).toBeCloseTo(1/6,3);expect(stats['2026-09-13'].minutes).toBeCloseTo(1/6,3);});
 it('ignored sessions disappear from stats but raw data remains',()=>{const x=fresh(),s=completed(x),w=new ObsidianWriter(x.store,x.config,x.dir);w.sync();s.status='ignored';x.store.save(s);w.sync();expect(aggregate(x.store,x.config.timezone)).toEqual({});expect(x.store.session(s.id)).toBeDefined();expect(w.files.read(x.config.obsidian.dailyFolder+'/2026-09-12.md')).toContain('ai_minutes: 0');});
 it('never changes a pre-existing daily frontmatter or prose',()=>{const x=fresh();completed(x);const w=new ObsidianWriter(x.store,x.config,x.dir);const p='日常记录/2026-09-12 星期六.md';const old='---\r\nai_minutes: 51\r\n---\r\n手写内容\r\n';w.files.write(p,old,null);w.sync();expect(w.files.read(p)?.startsWith(old)).toBe(true);expect(w.files.read(p)).toContain('ai_minutes: 51');});
});
